@startuml

class NameSorter {

+(static)readFile: BufferedReader
+(static)writeFile: BufferedWriter

+void main(args: String[])
+fileRead(inout inputFile: BufferedReader, fileName: String): ArrayList<String>
+fileWrite(inout outputFile: BufferedWriter, sortedString: ArrayList<String>, String fileName): BufferedWriter

}

@enduml